### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by guillermolechuga** [StevenRudenko/ActionsContentView#10]
Hi,

First of all, congrats for the library. This is the one that suits most kinds of app menus due to its many setting options.

The problem is that after mergin the last changes (since two or three of months ago) the scrolling performance dropped a lot.

Is this issue on the 'coming soon' roadmap?

Thanks.

**Comment by StevenRudenko** [comment]
Hello,
Interesting. I will take a look on this issue ASAP. Thanks for reporting.

**Comment by StevenRudenko** [comment]
I've committed code that makes performance better. Have an idea how improve it more.

**Comment by guillermolechuga** [comment]
Thanks for your quick response.

It really looks much smoother. I will take a look at the code, but the performance is good for me now.

Thanks!

**Comment by StevenRudenko** [comment]
It is nice to hear that it helped you. I will try find way how to make performance ever better.
For now I am closing this ticket.

Thanks for reporting!
