### ISSUE TITLE
content view and fullscreen videos

### ISSUE THREAD

**Issue by moviecityes** [StevenRudenko/ActionsContentView#13]
Webviewfragment incapable of handling properly HTML videos (full screen button freezes the video)

Ex. content viewed in webpage by webviewfragment that has lets say a youtube embed Iframe video the html player overrides it playng the video on press play button.

full screen button actually stops the video.

Just wanted to point that out not sure if its in the scope of the library but i leave it here anyway.

**Comment by StevenRudenko** [comment]
Sorry. It is out of scope of this sample project.
