### ISSUE TITLE
Would you able to show me how to implement or include your library in Eclipse?

### ISSUE THREAD

**Issue by jjhesk** [StevenRudenko/ActionsContentView#16]
I have done both ways
a) only using and include the jar file as the library on my codings
b) include the whole folder called "ActionsContentViewLib" as the library in the workplace.

There are errors found from the runtime testing. 
1) Source not found.. 

2) [2013-06-27 15:41:50 - ActionsContentViewLib] Could not find ActionsContentViewLib.apk!
the apk file located in the bin was not found.

What is the correct way to include your library in the workplace??

**Comment by StevenRudenko** [comment]
What IDE are you using?

**Comment by StevenRudenko** [comment]
Found that at ticket title.
You should use Eclipse menu File->Import->Android->Existing Android Code into Eclipse. Browse for library folder and import it. Now you should link library project with yours.
