### ISSUE TITLE
ListFragment is Drawn over the ActionContentView

### ISSUE THREAD

**Issue by ghost** [StevenRudenko/ActionsContentView#17]
Hey I tried to add a ListFragment to the ActionContentView and it just overlays the navigation menu.

See the screenshot:

![device-2013-07-29-215943](https://f.cloud.github.com/assets/1547516/874335/79fe6534-f889-11e2-850c-c7fcd4ca7479.png)
![device-2013-07-29-215929](https://f.cloud.github.com/assets/1547516/874337/7b2fdc08-f889-11e2-80e7-e4f71386907f.png)

**Comment by ghost** [comment]
Update: This isn't a bug, you just need to set the background color for the listfragment's listview to white or something.

Cheers

**Comment by StevenRudenko** [comment]
Nice. I would like to see your file manager after it is finished. I like first screens you've posted!

**Comment by ghost** [comment]
Sure mate I'll let you know when it's released. Thanks for the awesome library :)
