### ISSUE TITLE
Sample project has bug when device is rotated

### ISSUE THREAD

**Issue by ghost** [StevenRudenko/ActionsContentView#18]
I noticed in the sample for the library if you rotate the device a few times the shown fragment will be messed up.

To reproduce this: Start the app > Choose settings > rotate device > choose about > rotate device. Now you should see the setting fragment although about was chosen.

It's lying somewhere in the updateContent() method but I couldn't find out whats the issue.

**Comment by StevenRudenko** [comment]
Thanks for reporting. Issue should be fixed now.
