### ISSUE TITLE
How in the world do you add a category?

### ISSUE THREAD

**Issue by MBQ-** [StevenRudenko/ActionsContentView#19]
Hey!

After going through your code numerous times, I can't for the life of me figure out how the heck you added categories. ('Bookmarks').

If you could please show me how, or give me a link to where I could find my answer, I'd really appreciate it.

Thank you so much for such an awesome library. Use it in nearly all the apps I create.
- Kyler

**Comment by StevenRudenko** [comment]
Please take a look on https://github.com/StevenRudenko/ActionsContentView/blob/master/ActionsContentViewExample/res/values/arrays.xml
There are arrays with names: actions_icons, actions_names, actions_links. actions_links holds information in Uri format about content type. You will see category://bookmarks and category://settings there.

Next step is https://github.com/StevenRudenko/ActionsContentView/blob/master/ActionsContentViewExample/src/sample/actionscontentview/adapter/ActionsAdapter.java
There are VIEW_TYPE_CATEGORY, VIEW_TYPE_SETTINGS and VIEW_TYPE_SITES. We can define content type by Uri: take a look public int getItemViewType(int position) method.

Last point is public View getView(int position, View convertView, ViewGroup parent) method where views are inflated depending on content type.

I hope this would help you to find answer for your question.

**Comment by MBQ-** [comment]
Sick.

Thanks bro. :)

**Comment by MBQ-** [comment]
One more question if you don't mind.

I know this one may be a lottt to cover, so if you don't have time, I understand.

I have my app here: https://github.com/MBQ-/MBQs-CPU-Guide

As I'm still very new at Java, How would I re-route parts of the ListView to the ActionsAdapter?  Cause, y'know, you cant extend a FragmentActivity and implement BaseAdapter. ;p

Again, if you dont have time, Ill do what I can to find the answer, but either way.. thanks a TON for your help already bro.

**Comment by StevenRudenko** [comment]
I think you need create separate Adapter class and use it at you Activity.

**Comment by MBQ-** [comment]
Alright. Looks like I have some researching to do! 

Thanks again for your help.
