### ISSUE TITLE
Page scroll width

### ISSUE THREAD

**Issue by phcaze** [StevenRudenko/ActionsContentView#2]
Hi, thanks for this library, it's very usefull!
It's possible to set the "scroll width" of the page?

Thanks
Regards

**Comment by StevenRudenko** [comment]
Hello,

What do you mean by 'scroll width'? Can you provide an image or some
description of this feature?

Thanks,
Steven

## 

Steven Rudenko
Software developer
Email: steven.rudenko@gmail.com

**Comment by phcaze** [comment]
It's possible to set the width of the menu on the left in a way that the slide effect stops at the middle of the page for example, instead of at the right? Like in the picture:
![Screenshot_2012-12-19-09-08-03](https://f.cloud.github.com/assets/2863670/21502/54007f8e-49b6-11e2-8f37-0519d5820706.png)

**Comment by StevenRudenko** [comment]
Hello,

Yes, it is possible. You should use 'actions_width' spacing type and set
width value to spacing like this:
<shared.ui.actionscontentview.ActionsContentView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/actionsContentView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        *app:spacing_type="actions_width"
        app:spacing="150dp"*
        app:actions_layout="@layout/actions"
        app:content_layout="@layout/content" />

Every this value you can set realtime using
setSpacingType(SPACING_ACTIONS_WIDTH) and setSpacingWidth(width).

I hope it helped you.

Kind regards,
Steven

## 

Steven Rudenko
Software developer
Email: steven.rudenko@gmail.com

**Comment by mitesh-shah** [comment]
Thank u....it's working....:) as i wanted.....
