### ISSUE TITLE
Sliding menu with fragmentactivity

### ISSUE THREAD

**Issue by z5947878** [StevenRudenko/ActionsContentView#27]
Hi!

How should I coding about sliding menu with fragmentactivity without change page like facebook?

your code have what I thought, but that is fragment.

Your fragmentactivity will change the page, but fragment won't.

So, how should I do like fragment won't change the page? Cuz my code is fragmentactivity.

I mean call a different fragmentactivity in one activity from slidemenu..

**Comment by StevenRudenko** [comment]
Hello,

If you want switch to another activity by actions menu click you need make next changes:
1) Create Base activity that would handle switching by actions menu click. It should have ActionsContentView. You can create abstract method to get content layout id and set it to ActionContentView while activity onCreate.
2) Base activity should remove (override) animation while switching to new activity so user will not notice activity switching.
3) newly opened activity should have actions menu opened on start and launch hide it when become visible at first time. it would emulate closing of actions at place.
4) Extend all your activities from Base one.

Sorry I have no time to create example for you. Probably I will have some on weekend.
Anyway now you have way to make it real.

Regards,
Steven

**Comment by z5947878** [comment]
thx man, but I can not image It. looks like very complexity lol

**Comment by StevenRudenko** [comment]
well, keeping everything as activity view instead of fragments makes any solution not flexible.
better way move your code fragments but it can take more time. :)

**Comment by z5947878** [comment]
alrite

**Comment by z5947878** [comment]
back to the point. does slide menu need to keep it as activity intead of fragment?

**Comment by StevenRudenko** [comment]
sorry I don't get. what does slide menu need to keep? you can use ActionContentView in any layout.
it is just a custom view. your questions was about: can one activity include another one inside itself. Answer is NO. It is not possible and seems never become possible.

**Comment by z5947878** [comment]
okay thx body

**Comment by z5947878** [comment]
well can I ask for another question? I wanna put my customized title bar in evey fragment. How should I do?
And off course It can call out the actioncontentview.

**Comment by StevenRudenko** [comment]
I think you need create BaseFragment which will handle everything about action bar and extend all other from it.

**Comment by z5947878** [comment]
Okay I'll try it
