### ISSUE TITLE
action content view with underline

### ISSUE THREAD

**Issue by z5947878** [StevenRudenko/ActionsContentView#28]
How to creat underline like facebook on action content view?

please check the pic.

The last category hasn't underline and the action title has the blank which is above it.

![tjczk 1](https://f.cloud.github.com/assets/5245908/1021105/1c0b8c02-0ce0-11e3-82bf-4faad01e44f2.jpg)

**Comment by ghost** [comment]
You can add a divider view as the last element in your Adapter's array.

**Comment by z5947878** [comment]
I dont gey it, in the case, can u give me a example?

**Comment by StevenRudenko** [comment]
http://stackoverflow.com/ is better place for such questions as far it is not related to library.
