### ISSUE TITLE
how can I use ActionsContentView in my project

### ISSUE THREAD

**Issue by hdamis** [StevenRudenko/ActionsContentView#29]
can you please write a document in detail how can I use ActionsContentView in my project.

**Comment by StevenRudenko** [comment]
Hello, sure. I will do that this week.

**Comment by hdamis** [comment]
Thanks,

**Comment by hdamis** [comment]
Dear Steven,
I want to use your actionsContentView in my project. so I think I have to import your jar file to my project then what I have to do to include actionsContentView in my project. I need it ASAP.
Thanks

**Comment by StevenRudenko** [comment]
you can't use library as jar. it needs some resources to be use it at xml layouts.
you should import ActionsContentViewLib into your workspace and link it to your main project as Android library project.

**Comment by hdamis** [comment]
how to  link it to your main project as Android library project., and after linking ActionsContentViewLib  to my project how to use your ActionsContentView in my project. 
Thanks,

**Comment by StevenRudenko** [comment]
here is way how you can import and link ActionsContentView library: https://github.com/StevenRudenko/ActionsContentView/issues/34#issuecomment-24498731

**Comment by TacticalTwerking** [comment]
hi,is any light ActionsContentView as a jar available here.

**Comment by StevenRudenko** [comment]
Hello,

Yes. It is possible to do. You should remove add resources from
ActionsContentView library project and resolve conflicts after that.
As far as you probably know Android can generate JAR for library project if
there is no resources included into it.

Kind regards,
Steven

## 

Steven Rudenko | Software engineer
e. steven.rudenko@gmail.com | p. +380 63 2636053

**Comment by TacticalTwerking** [comment]
i'll try, thanks for your enthusiasm dude

**Comment by StevenRudenko** [comment]
Hello,

What problems do you have?

Regards,
Steven

## 

Steven Rudenko | Software engineer
e. steven.rudenko@gmail.com | p. +380 63 2636053
