### ISSUE TITLE
how to implement your library to support right menu at theame activity just like path on ios ???

### ISSUE THREAD

**Issue by liufsd** [StevenRudenko/ActionsContentView#3]
i want to creat two menu in the mainactivity at the theam time .just like the app of path on ios. But I do not know how to do that.I think you can help me.

i wish you will help me .../

Thanks.

**Comment by StevenRudenko** [comment]
It is not implemented ATM. it is in my features to develop list. Sorry I don't have any estimations for you about when it will be available.

Kind regards!

**Comment by liufsd** [comment]
Ok.thank you!
