### ISSUE TITLE
adding new category and items

### ISSUE THREAD

**Issue by hdamis** [StevenRudenko/ActionsContentView#31]
I like your ActionsContentView and I want to implement in my project. first I need to add on top new category with some items. so I did like this but I got an error.
1. 
I add
<string-array name="actions_links">
         <item>category://Service</item>
         <item>settings://Rent</item>
         <item>settings://Book</item>
        <item>category://settings</item>
.....................................................................
2. I add 
 
    <string name="action_service">Service</string>
    <string name="action_about">About</string>
...........................................................................

3.I add in sample.actionscontentview.adapter ActionsAdapter

 private static final int VIEW_TYPES_SERVICE = 4;

4.
 @Override
  public int getItemViewType(int position) {
    final Uri uri = Uri.parse(mUrls[position]);
    final String scheme = uri.getScheme();
    if ("category".equals(scheme))
      return VIEW_TYPE_CATEGORY;
    else if ("settings".equals(scheme))
      return VIEW_TYPE_SETTINGS;
    else if ("service".equals(scheme))
        return VIEW_TYPES_SERVICE;
      return VIEW_TYPE_SITES;
  }

some items in my post was hidden so please see the image 

http://www.4shared.com/photo/tLuosLvB/action.html

please help me doing this.... Thanks

**Comment by StevenRudenko** [comment]
Hello.

Thank you for question not related to ActionsContentView library project.

As far I can see you are not familiar with Adapter item types usage. Please take a look on these two links to get more information about it.
http://developer.android.com/reference/android/widget/BaseAdapter.html#getItemViewType%28int%29
http://logc.at/2011/10/10/handling-listviews-with-multip%60le-row-types/
