### ISSUE TITLE
Unfortunately, ActionsContentView stopped,

### ISSUE THREAD

**Issue by hdamis** [StevenRudenko/ActionsContentView#32]
I tried to add another three itmes under setting category, but then the apps stopped working, the second question where I can find the setting file to create more categories. 
finally.
I created a new login.xml layout and I want to link item settings://login item to login.xml.( we need an example) I see that many needs that 

I use  ActionsContentViewExample.
please don't forward me to read any thing else I need your answer thanks,.

**Comment by StevenRudenko** [comment]
Hello, what kind of example for ActionContentView usage do you need?

**Comment by StevenRudenko** [comment]
Closing this issue as far there is no steps to reproduce this problem and it is wrong place to post such questions.
Please use http://stackoverflow.com/ to any questions not related to ActionsContentView library.
