### ISSUE TITLE
NavigationSample

### ISSUE THREAD

**Issue by hdamis** [StevenRudenko/ActionsContentView#33]
why when I install ActionsContentView on my mobile using Eclisps the NavigationSample will installed automatically .
and when I remove it from my project the project will not run due to errors. any idea how to remove it from the project.

**Comment by StevenRudenko** [comment]
It seems you use wrong projects configuration. Please use ActionsContentViewLib with ActionsContentViewExample.

Could you don't post such questions as issue here? Please write emails in this case.
