### ISSUE TITLE
Disable Swipe

### ISSUE THREAD

**Issue by rnselv1** [StevenRudenko/ActionsContentView#35]
How can i disable swipe?
I tried viewActionsContentView.setSwipingEnabled(false); but that has no effect. On the res file I couldn't find an attribute to disable swipe.

**Comment by StevenRudenko** [comment]
Hello. I've just tried viewActionsContentView.setSwipingEnabled(false); and it worked well for me.
There is no attribute to disable swipe indeed.

Could you be more specific with scenario to reproduce problem?

**Comment by StevenRudenko** [comment]
Please make sure that you call viewActionsContentView.setSwipingEnabled(false); on UI thread.

**Comment by rnselv1** [comment]
It worked. My bad.

Thanks,
Roshan

**Comment by StevenRudenko** [comment]
No problem. :)

**Comment by StevenRudenko** [comment]
I've added attribute to set swiping enabled/disabled
