### ISSUE TITLE
How to Link to activity

### ISSUE THREAD

**Issue by drlucfier** [StevenRudenko/ActionsContentView#36]
How to Link an item from array file with a specific layout

**Comment by StevenRudenko** [comment]
As far I understand your question you want use activities to switch between them on Actions item click.

Here is comment I've wrote for similar question: https://github.com/StevenRudenko/ActionsContentView/issues/27#issuecomment-23172667

I hope this would give you picture of way to go.

**Comment by drlucfier** [comment]
no i did not make it clear 

the item in side menu all linked to web view i can not link any item to layout i try to modify the array file but i couldn't handle it correct

Sorry for question but i in beginning of learning

**Comment by StevenRudenko** [comment]
Could you describe in steps what you want to achieve? It is not clear for me what you what to get.

**Comment by drlucfier** [comment]
i need to connect items in side menu with layout i choose as for youtube i need it not to open http://youtube.com i need it to open youtube.xml in layout folder

i try in array file but it not working with me

**Comment by StevenRudenko** [comment]
Okay. You should use fragments with custom layouts. Take a look how it is done for:
[AboutFragment](https://github.com/StevenRudenko/ActionsContentView/blob/master/ActionsContentViewExample/src/sample/actionscontentview/fragment/AboutFragment.java)
[SandboxFragment](https://github.com/StevenRudenko/ActionsContentView/blob/master/ActionsContentViewExample/src/sample/actionscontentview/fragment/SandboxFragment.java)

There is method used to change content [ExamplesActivity.updateContent(Uri uri)](https://github.com/StevenRudenko/ActionsContentView/blob/master/ActionsContentViewExample/src/sample/actionscontentview/ExamplesActivity.java#L118)

**Comment by drlucfier** [comment]
thank you very much i will try and tell you the result

Thanks

**Comment by drlucfier** [comment]
i try a lot but couldn't do it correct can you help me with a small tutorial even a paid tutorial no problem for me

**Comment by StevenRudenko** [comment]
Please email me about details of what you want to get. I will try help you for free. This project was not created to earn money.
