### ISSUE TITLE
The ImageButton open or close menu bug... when you click it 

### ISSUE THREAD

**Issue by liufsd** [StevenRudenko/ActionsContentView#4]
Here is my log:

01-15 16:42:37.479: D/memalloc(7779): /dev/pmem: Mapped buffer base:0x4be0a000 size:9216000 offset:7680000 fd:58
01-15 16:42:37.559: E/dalvikvm(7779): GC_FOR_ALLOC freed 123K, 8% free 9970K/10787K, paused 2ms+2ms
01-15 16:42:37.879: D/memalloc(7779): /dev/pmem: Mapped buffer base:0x4d4d7000 size:16465920 offset:14929920 fd:61
01-15 16:42:38.659: D/memalloc(7779): /dev/pmem: Mapped buffer base:0x4ccd3000 size:4608000 offset:3072000 fd:64
01-15 16:42:39.739: E/TAG(7779): ___
01-15 16:42:39.739: E/TAG(7779): _viewActionsContentView.showActions()__
01-15 16:42:50.429: E/TAG(7779): ___
01-15 16:42:50.429: E/TAG(7779): **viewActionsContentView.isActionsShown()_true
01-15 16:42:54.089: E/TAG(7779): ___
01-15 16:42:54.089: E/TAG(7779): _viewActionsContentView.showActions()**
01-15 16:42:57.189: E/TAG(7779): ___
01-15 16:42:57.189: E/TAG(7779): **viewActionsContentView.isActionsShown()_true
01-15 16:42:58.449: E/TAG(7779): ___
01-15 16:42:58.449: E/TAG(7779): _viewActionsContentView.showActions()**
01-15 16:42:59.549: E/TAG(7779): ___
01-15 16:42:59.549: E/TAG(7779): **viewActionsContentView.isActionsShown()_true
01-15 16:43:00.649: E/TAG(7779): ___
01-15 16:43:00.649: E/TAG(7779): _viewActionsContentView.showActions()**
01-15 16:43:01.669: E/TAG(7779): ___
01-15 16:43:01.669: E/TAG(7779): **viewActionsContentView.isActionsShown()_true
01-15 16:43:02.549: E/TAG(7779): ___
01-15 16:43:02.549: E/TAG(7779): __viewActionsContentView.isActionsShown()_true
01-15 16:45:31.479: E/TAG(7779): ___
01-15 16:45:31.479: E/TAG(7779): _viewActionsContentView.showActions()**

OK .  the last :
01-15 16:43:01.669: E/TAG(7779): __viewActionsContentView.isActionsShown()_true
01-15 16:43:02.549: E/TAG(7779): ___
01-15 16:43:02.549: E/TAG(7779): __viewActionsContentView.isActionsShown()_true

 so . i  should click the button twice and then it can show left menu
here is  you code:
 public void onActionsButtonClick(View view) {
    if (viewActionsContentView.isActionsShown())
      viewActionsContentView.showContent();
    else
      viewActionsContentView.showActions();
  }

what's wrong? tell me please ..
Thanks !

**Comment by liufsd** [comment]
And I found :if you scroll the view at first ,and the click the button to close left menu , ok, and then you click button to show left menu ,you will find this bug. you should click twice....
if you not scorll, you can just only click the button to open  and show the left menu . when you click it at seventh times ,it also show this bug....

**Comment by liufsd** [comment]
OK.I get it. i use a state ...

**Comment by StevenRudenko** [comment]
Here is scenario I found:
ActionsContentView (view in future) is opened (actions are hidden)
1 click on button - view closing started (closing animation started)
2 click on button - view closing in progress (closing animation in progress) - click is 'ignored'
3 click on button - view was closed and opening is started (animation of opening view is started)
...

Please confirm that I got your problem right. If you have any suggestions how to improve workflow of view I would appreciate that.

**Comment by liufsd** [comment]
i update you code of ActionsContentView.class
    /**
     \* menu state open or close content show --false content hid --true
     \* 
     */
    private boolean mMenuOpenstate = false;
when you use completeScrolling :if (startX > middle) {

```
            mMenuOpenstate = false;
            Log.e(TAG, "show" + "mMenuOpenstate " + mMenuOpenstate);
            showContent(mFlingDuration);
        } else {

            mMenuOpenstate = true;
            Log.e(TAG, "hid" + "mMenuOpenstate " + mMenuOpenstate);
            hideContent(mFlingDuration);
        }
```

**Comment by liufsd** [comment]
But i found another problem , i call it "magical bug".
when i use a listview on fragment . if you set listview  android:layout_height="wrap_content" or "fill_parent", the listview baseadapter will catch a problem that  getview method return postion is wrong.
my log:
01-17 15:52:14.997: V/MyListViewBase(995): getView 0 null
01-17 15:52:15.027: V/MyListViewBase(995): getView 0 android.widget.LinearLayout@43e81650
01-17 15:52:15.038: V/MyListViewBase(995): getView 0 android.widget.LinearLayout@43e81650
...........
Sometimes i set baseadabter getcout return 4, but the the position return (0123  0123 ...) .i mean: it will getview again and again , but the postiong is wrong.

but my baseadapter getcount()  just have only one item data. what' the problem?
public class MyAdapter extends BaseAdapter {
    private LayoutInflater mInflater  
        public MyAdapter(Context context) {
        this.mInflater = LayoutInflater.from(context);
    }

```
@Override
public int getCount() {
```

// just for testing.....
        return 1;  
    }

```
@Override
public Object getItem(int position) {
    return null;
}

@Override
public long getItemId(int position) {
    return 0;
}

@Override
public View getView(final int position, View convertView, ViewGroup parent) {
     ViewHolder holder;        
     Log.v("MyListViewBase", "getView " + position + " " + convertView);
```

.............................
...
The first time I found this problem, i do not know how to solve this problem....
Thanks.

**Comment by liufsd** [comment]
Here is my code , you can test it....
....................................................................
xml:  
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical" >

```
    <TextView
        android:id="@+id/result"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <ListView
        android:id="@+id/ls"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:cacheColorHint="#efefef" >
    </ListView>
</LinearLayout>
```

..........................................................................................
fragment:  
@Override
    public void onActivityCreated(Bundle savedInstanceState) {

```
    super.onActivityCreated(savedInstanceState);
      MyAdapter mAdapter = new MyAdapter(getActivity());
           Mlistview.setAdapter(mAdapter);/
}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
        Bundle savedInstanceState) {
    viewRoot = inflater.inflate(R.layout.fragment_testsanbox, container,
            false);
    resulTextView = (TextView) viewRoot.findViewById(R.id.result);
                              Mlistview=(ListView)viewRoot.findViewById(R.id.ls);
    if (getIsFristLoad() && null != getCommand()) {
        getCommand().request();
    }

    return viewRoot;
}
```

Thanks for your help.

**Comment by liufsd** [comment]
i do not know  how to solve this problem. when the fragment create , i found the listview adapter  getcount first and the getview return position println 0 and next print 1 .0 1 .0..1  again and again....
you can add listview on your fragment,you will find this problem.
First time i got this problem. 
i wish you can tell me ...
Thanks.

**Comment by liufsd** [comment]
Hi.
. i get problem , and solve it by myself.
you must set the listview hight "match" like this :android:layout_height="match_parent"  in your layout.xml
