### ISSUE TITLE
How to call WebView and call a specific html file?

### ISSUE THREAD

**Issue by generalistcodes** [StevenRudenko/ActionsContentView#40]
I want to replace the about fragment with a webview and call specific page "file:///android_asset/www/login.html" how to do this?

**Comment by StevenRudenko** [comment]
Replace settings://about by file:///android_asset/www/login.html here :
https://github.com/StevenRudenko/ActionsContentView/blob/master/ActionsContentViewExample/res/values/arrays.xml#L106

Please don't post questions here. Write private email or as community on http://stackoverflow.com/

**Comment by generalistcodes** [comment]
I already figure it out.Thanks :)

**Comment by generalistcodes** [comment]
This library is so cool bro :+1:
