### ISSUE TITLE
ActionsContentView with googlemaps

### ISSUE THREAD

**Issue by conbon** [StevenRudenko/ActionsContentView#42]
I am trying to implement the menu with google maps as my main fragment activity. Although when I have both the actionscontentview and mapfragment in the layout xml the map displays but I am not able to swipe the menu in from the left. When I increase the margin on the left side of the map I can see the menu partially, but only to the edge of the map.

Is this maybe because the map is picking up the swipe?

Any help appreciated.

**Comment by StevenRudenko** [comment]
Hello Conal,

Do you have map fragment as content view of ActionsContentView? You can
enable swipe from edge for menu so ACV will handle menu opening from screen
edge but there will be ability to scroll map as well.

Best regards,
Steven

## 

Steven Rudenko | Software engineer
e. steven.rudenko@gmail.com | p. +380 63 2636053

**Comment by conbon** [comment]
Hi Steven,

I had the map fragment in my activity_main. Put it into the content view and worked. It actually doesn't open as smoothly with the map there but works nonetheless. Great work on the menu.

Thanks,
Conal
