### ISSUE TITLE
webview hardware back button closes app

### ISSUE THREAD

**Issue by moviecityes** [StevenRudenko/ActionsContentView#9]
In you example ActionsContentViewExample if one is navigating trough the webview pages and uses the hardware back button it closes the app instead of navigating back in the browsing history on the webpage.
fixed #9

**Comment by StevenRudenko** [comment]
Webview was made just for demonstration of switching using actions view. I didn't want make complex application that would work as browser.
Thanks for reporting this issue. There is simple fix for it. I would commit it next week.

**Comment by moviecityes** [comment]
Right :) it was just a pointer, i felt the need of the navigation functions wen browsing and testing your work (which is great by the way !!! ) keep it up and greeting from Portugal :+1:

**Comment by StevenRudenko** [comment]
I've added this feature. Please try it and close ticket if it fine.
P. S. I've uploaded update to Google Play. It should be available in few hours.

**Comment by moviecityes** [comment]
Perfect!
fixed #9
